### ISSUE TITLE
Validate the format of the answer

### ISSUE THREAD

**Issue by ocoke** [ocoke/CranSurvey#5]

**Comment by oCoke** [comment]
## Plain Text

- `string_plain`: Plain text, up to 512 characters (default).
- `string_plain_max_[num]`: Plain text, up to `[num]` characters.
- `string_plain_min_[num]`: Plain text, at least `[num]` characters.
- `string_plain_[n1]:[n2]`: Plain text, at least `[n1]` characters and up to `[n2]` characters.

## Number

- `num_int`: Number, integers.
- `num_float`: Number, can be decimal.
- `num_min_[n1]`: Number, not less than `[n1]`.
- `num_max_[n1]`: Number, not greater than `[n2]`.
- `num_[n1]:[n2]`: Number, from `[n1]` to `[n2]`.

## Rating

- `rating_5`: Rating from 1 to 5.
- `rating_10`: Rating from 1 to 10.
- `rating_[n1]:[n2]`: Rating from `[n1]` to `[n2]`.

## Email

- `string_email`: Email address.

## Phone Number*

- `string_phone_[area]`: Phone number for area code `[area]`.

## Radio

- `radio_[q1],[q2],[q3];`: Radio, text from `[q1]`, `[q2]`, and `[q3]`.


## Multiple

- `multi_[q1],[q2],[q3];`: Multiple, text from `[q1]`, `[q2]`, and `[q3]`.


## Hidden

- `hidden`: Hidden for Radio or Multiple.

**Comment by oCoke** [comment]
## Date

- `date`

## Time

- `time`

**Comment by ocoke** [comment]
```json
"types": {
  "short_answer": "Short Answer",
  "paragraph": "Paragraph",
  "multiple": "Multiple Choice",
  "checkboxes": "Checkboxes",
  "dropdown": "Dropdown",
  "file": "File Upload",
  "linear": "Linear Scale",
  "date": "Date",
  "time": "Time"
}
```
